steps:
    - name: node:20.10.0
      entrypoint: npm
      args: ["ci"]
      id: "install"

    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy", "app.yaml"]
      waitFor: ["install"]

timeout: 1800s
